<a href="https://colab.research.google.com/github/kiaracondoy-bit/Algebra-Lineal/blob/main/Matriz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import datetime

# Replace "Your Name" with your actual name
name = "Kiara Salomé Condoy Morocho"
now = datetime.datetime.now()

print(f"Nombre: {name}")
print(f"Fecha: {now.strftime('%Y-%m-%d')}")
print(f"Hora: {now.strftime('%H:%M:%S')}")

Nombre: Kiara Salomé Condoy Morocho
Fecha: 2025-10-20
Hora: 17:45:33


In [12]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[1, 0],
              [6, -2],
              [-1, 4]])

B = np.array([[2, -5, 1, -2],
              [3, 2, 0, -1]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
#suma = A + B
#print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
#resta = A - B
#print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
#escalar = 2
#producto_escalar = escalar * A
#print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor=(A[0,0] * B[0,0] + A[0,1] * B[1,0])

print("El producto de C[0,0] es ",valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)



Matriz A:
 [[ 1  0]
 [ 6 -2]
 [-1  4]]

Matriz B:
 [[ 2 -5  1 -2]
 [ 3  2  0 -1]]

 Producto matricial (A * B):
 [[  2  -5   1  -2]
 [  6 -34   6 -10]
 [ 10  13  -1  -2]]
El producto de C[0,0] es  2
