<a href="https://colab.research.google.com/github/kiaracondoy-bit/Algebra-Lineal/blob/main/Matriz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import numpy as np
import datetime
import pytz # Import the pytz library for timezone handling

# Replace "Your Name" with your actual name
name = "Kiara Salomé Condoy Morocho"
carrera = "Computación - Primer ciclo"
# Get the timezone for Ecuador
ecuador_timezone = pytz.timezone('America/Guayaquil')
now_ecuador = datetime.datetime.now(ecuador_timezone)


print(f"Nombre: {name}")
print(f"Carrera: {carrera}")
print(f"Fecha: {now_ecuador.strftime('%Y-%m-%d')}")
print(f"Hora: {now_ecuador.strftime('%H:%M:%S')}")


# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2],
              [1, 3, 5]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
suma = A + B
print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
resta = A - B
print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Nombre: Kiara Salomé Condoy Morocho
Carrera: Computación - Primer ciclo
Fecha: 2025-10-22
Hora: 07:39:37
Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Suma (A + B):
 [[5 6 7]
 [5 3 3]
 [1 2 7]]

 Resta (A - B):
 [[-1  2  5]
 [-3  3  7]
 [-1 -4 -3]]

 Multiplicación por escalar (2 * A):
 [[ 4  8 12]
 [ 2  6 10]
 [ 0 -2  4]]

 Producto matricial (A * B):
 [[28 22 24]
 [20 17 20]
 [-2  6 12]]
